import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center">
        <h1 className="text-2xl font-bold underline">Next Starter</h1>
        <p>
          A starter template using next.js, typescript, axios, docker, and
          tailwindcss.
        </p>
      </div>
    </div>
  );
};

export default Home;
